//! rdev → protocol translation.

use protocol::MouseButton;

pub fn rdev_button_to_proto(b: rdev::Button) -> Option<MouseButton> {
    Some(match b {
        rdev::Button::Left => MouseButton::Left,
        rdev::Button::Right => MouseButton::Right,
        rdev::Button::Middle => MouseButton::Middle,
        rdev::Button::Unknown(_) => return None,
    })
}

/// Translate rdev's named keys to HID Usage IDs (page 0x07). Covers the same
/// subset as `input-inject::keymap`. Unknown keys return `None`.
pub fn rdev_key_to_hid(k: rdev::Key) -> Option<u16> {
    use rdev::Key::*;
    Some(match k {
        KeyA => 0x04,
        KeyB => 0x05,
        KeyC => 0x06,
        KeyD => 0x07,
        KeyE => 0x08,
        KeyF => 0x09,
        KeyG => 0x0A,
        KeyH => 0x0B,
        KeyI => 0x0C,
        KeyJ => 0x0D,
        KeyK => 0x0E,
        KeyL => 0x0F,
        KeyM => 0x10,
        KeyN => 0x11,
        KeyO => 0x12,
        KeyP => 0x13,
        KeyQ => 0x14,
        KeyR => 0x15,
        KeyS => 0x16,
        KeyT => 0x17,
        KeyU => 0x18,
        KeyV => 0x19,
        KeyW => 0x1A,
        KeyX => 0x1B,
        KeyY => 0x1C,
        KeyZ => 0x1D,
        Num1 => 0x1E,
        Num2 => 0x1F,
        Num3 => 0x20,
        Num4 => 0x21,
        Num5 => 0x22,
        Num6 => 0x23,
        Num7 => 0x24,
        Num8 => 0x25,
        Num9 => 0x26,
        Num0 => 0x27,
        Return => 0x28,
        Escape => 0x29,
        Backspace => 0x2A,
        Tab => 0x2B,
        Space => 0x2C,
        Minus => 0x2D,
        Equal => 0x2E,
        LeftBracket => 0x2F,
        RightBracket => 0x30,
        BackSlash => 0x31,
        SemiColon => 0x33,
        Quote => 0x34,
        BackQuote => 0x35,
        Comma => 0x36,
        Dot => 0x37,
        Slash => 0x38,
        CapsLock => 0x39,
        F1 => 0x3A,
        F2 => 0x3B,
        F3 => 0x3C,
        F4 => 0x3D,
        F5 => 0x3E,
        F6 => 0x3F,
        F7 => 0x40,
        F8 => 0x41,
        F9 => 0x42,
        F10 => 0x43,
        F11 => 0x44,
        F12 => 0x45,
        Home => 0x4A,
        PageUp => 0x4B,
        Delete => 0x4C,
        End => 0x4D,
        PageDown => 0x4E,
        RightArrow => 0x4F,
        LeftArrow => 0x50,
        DownArrow => 0x51,
        UpArrow => 0x52,
        ControlLeft => 0xE0,
        ShiftLeft => 0xE1,
        Alt => 0xE2,
        MetaLeft => 0xE3,
        ControlRight => 0xE4,
        ShiftRight => 0xE5,
        AltGr => 0xE6,
        MetaRight => 0xE7,
        _ => return None,
    })
}
